MSG_ERROR_INVALID_CELL = "Invalid cell for a cat or the mouse|Gato o ratón en posición no válida"
MSG_ERROR_GAMESTATUS = "Game status not valid|Estado no válido"
MSG_ERROR_MOVE = "Move not allowed|Movimiento no permitido"
MSG_ERROR_NEW_COUNTER = "Insert not allowed|Inseción no permitida"
MSG_ERROR_INVALID_LOGIN = "Username/password is not valid|Usuario/clave no válidos"
MSG_ERROR_DIFFERENT_PASSWORDS = "Password and Repeat password are not the same|La clave y su repetición no coinciden"
MSG_ERROR_INVALID_PASSWORD = "(?=.*too short)(?=.*at least 6 characters)(?=.*too common)"
MSG_ERROR_EXISTING_USER = "A user with that username already exists|Usuario duplicado"
ERROR_MESSAGE_ID = "msg_error"
MSG_ERROR_LOGIN_ID = "You couldn't log in properly|No has podido iniciar sesión"
ERROR_NOT_FOUND = "Sorry! Page not found|Página no encontrada! Perdona..."
GAME_SELECTED_SESSION_ID = "game_id"
MSG_ERROR_ANONYMOUS = "Action restricted to anonymous users|Servicio restringido a usuarios anónimos"
