# Generated by Django 2.1.5 on 2019-11-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='origin',
        ),
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
