# Generated by Django 2.1.5 on 2019-11-16 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.OneToOneField(default='user', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('games_as_cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_cat', to='datamodel.Game')),
                ('games_as_mouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_as_mouse', to='datamodel.Game')),
            ],
        ),
        migrations.RemoveField(
            model_name='counter',
            name='origin',
        ),
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
